[package]
name = "gpu-shell"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
rust-desktop-ui-core = { version = "0.1.0", path = "../../crates/ui-core" }
rust-desktop-ui-render-wgpu = { version = "0.1.0", path = "../../crates/ui-render-wgpu" }
winit.workspace = true
pollster.workspace = true
