[package]
name = "rust-desktop-ui-controls"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rust-desktop-ui-core = { version = "0.1.0", path = "../ui-core" }
rust-desktop-ui-layout = { version = "0.1.0", path = "../ui-layout" }
rust-desktop-ui-text = { version = "0.1.0", path = "../ui-text" }
