[package]
name = "controls-gallery"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
rust-desktop-ui-core = { path = "../../crates/ui-core", version = "0.1.0" }
rust-desktop-ui-controls = { path = "../../crates/ui-controls", version = "0.1.0" }
rust-desktop-ui-treegrid = { path = "../../crates/ui-treegrid", version = "0.1.0" }
rust-desktop-ui-text = { path = "../../crates/ui-text", version = "0.1.0" }
rust-desktop-ui-platform-winit = { path = "../../crates/ui-platform-winit", version = "0.1.0" }
