[package]
name = "rust-desktop-ui-text"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rust-desktop-ui-core = { version = "0.1.0", path = "../ui-core" }
parley.workspace = true
swash.workspace = true
unicode-segmentation.workspace = true
